[workspace]
resolver = "2"
members = [
    "cam-types",
    "cam-isp",
    "cam-hal",
    "cam-hal-android",
    "cam-hal-linux",
    "cam-core",
    "cam-onnx",
    "cam-motion",
    "cam-binder",
    "cam-app",
    "cam-disp",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
log = "0.4"
thiserror = "2"
env_logger = "0.10"
android_logger = "0.14"
