//! LensShadingBlock — compensates for lens vignetting (dark corners).
//!
//! Emits ONNX Mul node: output = input * shading_lut
//! The LUT is a [1,3,H,W] float32 radial gradient generated from calibration data.
//!
//! For a typical wide-angle lens, corners receive ~60-80% of center brightness.
//! The LUT inverts this: corner pixels get multiplied by 1.25-1.67 to equalize.

use crate::pipeline::IspBlock;
use crate::onnx::proto::Proto;

pub struct LensShadingBlock {
    pub id: String,
    pub prev: Option<Box<dyn IspBlock>>,
    pub next: Option<Box<dyn IspBlock>>,
    pub frame_tensor: String,
    pub input_source: String,
    /// LUT shape: [1, 3, H, W] where each channel has the same radial gain.
    /// Generated by `generate_radial_lut()`.
    pub lut_initializer: Option<Vec<u8>>,
    pub height: Option<i64>,
    pub width: Option<i64>,
}

impl LensShadingBlock {
    pub fn new() -> Self {
        Self {
            id: "lens_shading".into(),
            prev: None,
            next: None,
            frame_tensor: "LensShadingBlock/frame".into(),
            input_source: String::new(),
            lut_initializer: None,
            height: None,
            width: None,
        }
    }

    /// Set concrete dimensions and generate radial LUT.
    /// corner_gain: multiplier at corners (e.g. 1.5 = corners get 50% boost).
    /// center_gain: multiplier at center (usually 1.0).
    pub fn with_radial_lut(mut self, h: u32, w: u32, corner_gain: f32, center_gain: f32) -> Self {
        self.height = Some(h as i64);
        self.width = Some(w as i64);
        let lut = Self::generate_radial_lut(h, w, corner_gain, center_gain);
        let name = format!("{}/lut", self.tensor_ns());
        let init = Proto::tensor_proto_float(
            &name,
            &[1, 3, h as i64, w as i64],
            &lut,
        );
        self.lut_initializer = Some(init);
        self
    }

    /// Set a custom LUT (already packed as [1,3,H,W] f32).
    pub fn with_custom_lut(mut self, h: u32, w: u32, lut: Vec<f32>) -> Self {
        self.height = Some(h as i64);
        self.width = Some(w as i64);
        let name = format!("{}/lut", self.tensor_ns());
        let init = Proto::tensor_proto_float(
            &name,
            &[1, 3, h as i64, w as i64],
            &lut,
        );
        self.lut_initializer = Some(init);
        self
    }

    /// Generate a radial gain LUT that brightens corners.
    /// Uses a simple quadratic model: gain = center_gain + (corner_gain - center_gain) * r²
    fn generate_radial_lut(h: u32, w: u32, corner_gain: f32, center_gain: f32) -> Vec<f32> {
        let cx = (w as f32 - 1.0) * 0.5;
        let cy = (h as f32 - 1.0) * 0.5;
        let max_r_sq = cx * cx + cy * cy;
        let gain_range = corner_gain - center_gain;

        let mut lut = Vec::with_capacity((h * w * 3) as usize);
        for _c in 0..3 {
            for y in 0..h {
                for x in 0..w {
                    let dx = x as f32 - cx;
                    let dy = y as f32 - cy;
                    let r_sq = dx * dx + dy * dy;
                    let t = (r_sq / max_r_sq).min(1.0);
                    // Quadratic interpolation with soft knee
                    let gain = center_gain + gain_range * t;
                    lut.push(gain);
                }
            }
        }
        lut
    }
}

impl IspBlock for LensShadingBlock {
    fn id(&self) -> &str { &self.id }
    fn tensor_ns(&self) -> String { "LensShading".into() }
    fn frame_tensor(&self) -> Option<&str> { Some(&self.frame_tensor) }
    fn input_source(&self) -> Option<&str> { Some(&self.input_source) }
    fn set_input_source(&mut self, name: &str) { self.input_source = name.into(); }
    fn prev(&self) -> Option<&Box<dyn IspBlock>> { self.prev.as_ref() }
    fn set_prev(&mut self, block: Box<dyn IspBlock>) { self.prev = Some(block); }
    fn next(&self) -> Option<&Box<dyn IspBlock>> { self.next.as_ref() }
    fn set_next(&mut self, block: Box<dyn IspBlock>) { self.next = Some(block); }

    fn input_tensors(&self) -> Vec<String> {
        vec![self.input_source.clone()]
    }

    fn output_tensors(&self) -> Vec<String> {
        vec![self.frame_tensor.clone()]
    }

    fn graph_output_name(&self) -> Option<&str> {
        Some(&self.frame_tensor)
    }

    fn input_value_info(&self) -> Option<Vec<u8>> {
        Some(Proto::value_info(
            &self.input_source,
            &[Proto::tensor_dim_value(1), Proto::tensor_dim_value(3),
              Proto::tensor_dim_param("H"), Proto::tensor_dim_param("W")], 1))
    }

    fn output_value_info(&self) -> Option<Vec<u8>> {
        let (h, w) = match (self.height, self.width) {
            (Some(h), Some(w)) => (h, w),
            _ => return None, // Need concrete dims
        };
        Some(Proto::value_info(
            &self.frame_tensor,
            &[Proto::tensor_dim_value(1), Proto::tensor_dim_value(3),
              Proto::tensor_dim_value(h), Proto::tensor_dim_value(w)], 1))
    }

    fn nodes(&self) -> Vec<Vec<u8>> {
        let ns = self.tensor_ns();
        let lut_name = format!("{}/lut", ns);
        // Mul: input * radial_lut → output
        vec![Proto::node(
            "Mul",
            &[&self.input_source, &lut_name],
            &[&self.frame_tensor],
            &[],
        )]
    }

    fn initializers(&self) -> Vec<Vec<u8>> {
        let mut inits = Vec::new();
        if let Some(init) = &self.lut_initializer {
            inits.push(init.clone());
        }
        inits
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_radial_lut_center_is_identity() {
        // At center, gain should be ~center_gain (1.0)
        let lut = LensShadingBlock::generate_radial_lut(100, 100, 1.5, 1.0);
        // Center pixel: index 50*100 + 50 = 5050 per channel
        let center = lut[5050];
        assert!((center - 1.0).abs() < 0.05, "center gain should be ~1.0, got {}", center);
    }

    #[test]
    fn test_radial_lut_corners_are_brighter() {
        // Corners should have higher gain than center
        let lut = LensShadingBlock::generate_radial_lut(100, 100, 2.0, 1.0);
        let center = lut[5050]; // center
        let corner = lut[0];     // top-left corner
        assert!(corner > center, "corner gain {} > center gain {}", corner, center);
        assert!((corner - 2.0).abs() < 0.05, "corner gain should be ~2.0, got {}", corner);
    }

    #[test]
    fn test_radial_lut_is_symmetric() {
        let lut = LensShadingBlock::generate_radial_lut(100, 100, 1.5, 1.0);
        // Channel 0 and Channel 1 should be identical (same radial model)
        let ch0_center = lut[5050];
        let ch1_center = lut[100 * 100 + 5050];
        assert!((ch0_center - ch1_center).abs() < 1e-6, "channels should be symmetric");
    }

    #[test]
    fn test_lens_shading_onnx_emission() {
        let block = LensShadingBlock::new()
            .with_radial_lut(32, 32, 1.5, 1.0);
        let nodes = block.nodes();
        assert_eq!(nodes.len(), 1, "should emit exactly one Mul node");
        let inits = block.initializers();
        assert_eq!(inits.len(), 1, "should have one LUT initializer");
    }
}
