// bench_vulkanfuse.cpp — Benchmark MNN's VulkanFuse with our fused ISP SPIR-V
// Compile: cd ~/MNN/build_vk && g++ -std=c++17 -O2 -I../include -I.. -I../source -I../schema/current -I../3rd_party/flatbuffers/include -L./OFF ../softisp/vulkan_isp/bench_vulkanfuse.cpp -lMNN -lpthread -ldl -o bench_vulkanfuse
// Run: LD_LIBRARY_PATH=./OFF ./bench_vulkanfuse

#include <MNN/Interpreter.hpp>
#include <MNN/Tensor.hpp>
#include <MNN/HalideRuntime.h>
#include <MNN/MNNDefine.h>
#include <vector>
#include <iostream>
#include <chrono>
#include <fstream>
#include <cstring>
#include <cstdint>

// Embedded SPIR-V from fused_isp.comp (generated by glslangValidator)
// This would normally be loaded from file, but we embed it here for simplicity
// SPIR-V size: ~7200 bytes

// For now, we'll load from file
static std::vector<uint8_t> load_spirv(const char* path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    size_t size = f.tellg();
    f.seekg(0);
    std::vector<uint8_t> data(size);
    f.read(reinterpret_cast<char*>(data.data()), size);
    return data;
}

int main(int argc, char* argv[]) {
    const char* spirv_path = argc > 1 ? argv[1] : "/data/data/com.termux/files/home/softisp/vulkan_isp/fused_isp.spv";
    int iterations = argc > 2 ? atoi(argv[2]) : 10;

    std::cout << "=== MNN VulkanFuse ISP Benchmark ===" << std::endl;
    std::cout << "Loading SPIR-V from: " << spirv_path << std::endl;

    auto spirv = load_spirv(spirv_path);
    std::cout << "SPIR-V size: " << spirv.size() << " bytes" << std::endl;

    // Create MNN model in memory with Extra op containing SPIR-V
    // This uses MNN's C++ API to build the Net programmatically
    // But MNN's C++ API doesn't easily allow model creation from scratch
    // Instead, we use the existing VulkanFuse test approach

    // Create a simple ONNX model with Extra op, convert, then patch
    // For benchmark, let's use the existing isp_pipeline.mnn and replace the CFA ops

    std::cout << "\nNote: Full MNN model creation from C++ is complex." << std::endl;
    std::cout << "Alternative: Use Python to create model, then benchmark with C++" << std::endl;

    return 0;
}