[package]
name = "cam-binder"
version = "0.1.0"
edition = "2021"

[dependencies]
cam-types = { path = "../cam-types" }
cam-core = { path = "../cam-core" }
cam-hal-linux = { path = "../cam-hal-linux" }
log = { workspace = true }
thiserror = { workspace = true }

[dependencies.rsbinder]
version = "0.8"
optional = true

[features]
default = []
android = ["rsbinder"]
